pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: pull_request
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  test:
    image: node:boron
    environment:
      SDF_DATABASE_URL: "mongodb://127.0.0.1:27017"
    when:
      event: pull_request
    commands:
      - yarn
      - npm run build:prod
      - npm run lint

  rebuild-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: pull_request
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: docker
    secrets: [registry_username, registry_password]
    when:
      branch: master
      event: push
    commands:
      - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD registry.online.ntnu.no
      - docker build -t registry.online.ntnu.no/dotkom/super-duper-fiesta -f Dockerfile.prod .
      - docker push registry.online.ntnu.no/dotkom/super-duper-fiesta:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy:
    image: plugins/ssh
    host: nansen.online.ntnu.no
    port: 22
    user: root
    when:
      branch: master
      event: push
    script:
      - /usr/bin/docker pull registry.online.ntnu.no/dotkom/super-duper-fiesta:latest
      - /bin/systemctl restart super-duper-fiesta.service

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
