pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  setup:
    image: node:boron
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn
  
  build:
    image: node:boron
    group: testing
    when:
      event: pull_request
    commands:
      - npm run build:prod

  test:
    image: node:boron
    group: testing
    secrets: [codecov_token]
    environment:
      SDF_DATABASE_URL: "mongodb://127.0.0.1:27017"
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - yarn test
      - yarn codecov
  
  lint:
    image: node:boron
    group: testing
    when:
      event: [push, pull_request, tag, deployment]
    commands:
      - npm run lint

  rebuild-cache:
    image: drillster/drone-volume-cache
    pull: true
    when:
      event: [push, pull_request, tag, deployment]
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  
  release:
    image: docker
    secrets: [registry_username, registry_password, sdf_sentry_dsn_frontend]
    when:
      branch: master
      event: [push, tag, deployment]
      status: success
    commands:
      - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.online.ntnu.no
      - docker build -t registry.online.ntnu.no/dotkom/super-duper-fiesta -f Dockerfile.prod --build-arg SDF_SENTRY_DSN_FRONTEND .
      - docker push registry.online.ntnu.no/dotkom/super-duper-fiesta:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy:
    image: appleboy/drone-ssh
    pull: true
    secrets: [ssh_key]
    host: nansen.online.ntnu.no
    port: 22
    username: root
    key: ${SSH_KEY}
    command_timeout: 600
    when:
      branch: master
      event: [push, tag, deployment]
      status: success
    script:
      - /usr/bin/docker pull registry.online.ntnu.no/dotkom/super-duper-fiesta:latest
      - /bin/systemctl restart super-duper-fiesta.service

